export const sviProduktiPretraga=[
    "Slike",
    "Slike starije od 50 godina",
    "Svećnjaci vaze i pepeljare",
    "Rariteti",
    "Lusteri i lampe",
    "Porcelan",
    "Posuđe i escajg",
    "Igračke",
    "Figure",
    "Satovi",
    "Satovi | Ručni",
    "Satovi | Džepni",
    "Nakit",
    "Dokumenti",
    "Ikone i verske stvari",
    "Gobleni",
    "Grafike i crteži",
    "Duborezi i reljefi",
    "Skulpture",
    "Militarija | Ordenje, činovi, oznake",
    "Razglednice",
    "Kovani/Metalni novac",
    "Modelarstvo i maketarstvo",
    "Posteri i plakati",
    "Uređaji",
    "Novine",
    "Tablice",
    "Breweriana",
    "Zastave",
    "Diplome, pehari i medalje",
    "Papirni novac",
    "Modeli | Automobili",
    "Modeli | Kamioni i prikolice",
    "Modeli | Motocikli",
    "Modeli | Ostalo",
    "Električne mini železnice",
    "Kinder i druge figurice",
    "Suveniri",
    "Stakleni predmeti",
    "Ulaznice i pozivnice",
    "Ukrasne salvete",
    "Kristali i minerali",
    "Oruzije",
    "Narodna nošnja",
    "Ručni radovi",
    "Zanatski predmeti",
    "Muzički instrumenti",
    "Zaprežne kočije | Delovi",
    "Ćilimi i tapiserije",
    "Poljoprivredni predmeti",
    "Konzole",
    "Televizori",
    "Radio Uredjaji",
    "BIcikli",
    "Knjige",
    "Ostalo | Ne znam sta je"
];